// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated

pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant IS_EVEN_ID = bytes32(0x40c9e5425bc85337a2df2e8e551a5d98808b35490eabd3c156f2d4d0e8e49b42);
    bytes32 public constant MULTI_ROUND_HASH_ID =
        bytes32(0x930e7e05064bec9b441a76f41acca536f10be922f7dd2c9564268b33fc0d94f0);
}
